<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('clientes')->insert([
            'name' => 'Robherval Antunes',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Formosandrino Lifi Pereira',
            'name_mother' => 'Ant Plak',
            'name_father' => 'Hernan Abrr',
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'sexo' => 1,
            'est_civil' => 1,
            'cpf' => '523.592.190-90',
            'rg' => '34.168.123-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'formosandrino@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Chiko Berty',
            'name_mother' => 'Batisttw Afflw',
            'name_father' => 'Gertttt Juneer',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '523.592.190-90',
            'rg' => '34.168.123-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'formosandrino@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'BeearG Gqerty Fguua',
            'name_mother' => 'QueueIl Linnuss',
            'name_father' => 'FeliX Abgaaalerd',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '523.592.190-90',
            'rg' => '34.168.123-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'formosandrino@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Gerdwurd Hiull',
            'name_mother' => 'Ananeiast Kuruminoss',
            'name_father' => 'Pastrrer Hurlerr',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '523.592.190-90',
            'rg' => '34.168.123-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'formosandrino@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Gerley Hiuks Jut',
            'name_mother' => 'Arnir Blackaa',
            'name_father' => 'Pekeus Jaaka',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '844.864.250-30',
            'rg' => '43.640.708-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'gerley@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Fukiss Blatee Hock',
            'name_mother' => 'Hokert Gea',
            'name_father' => 'Deliss Flack',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '293.838.700-87',
            'rg' => '24.269.158-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Funes Morennn',
            'name_mother' => 'Kghjull Abdu',
            'name_father' => 'Azile Hyong',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Basic Arsivalee Rodrigues',
            'name_mother' => 'Kandu Jukiart',
            'name_father' => 'Kartej Juty Kured',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Lezereet Aniesta Juikiaa',
            'name_mother' => 'Antrofada Neo Neorl',
            'name_father' => 'Kreee Bob Nerte',
            'sexo' => 2,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Giurlecley Chilen Chilen II',
            'name_mother' => 'Herlele Jas Jasey',
            'name_father' => 'Marshall Centure',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Andoninho Vila Sabiano Brasil',
            'name_mother' => 'Caiçara da Silva',
            'name_father' => 'Romano de Jesus',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Kerlito Alves Bituk',
            'name_mother' => 'Contradis Rulian',
            'name_father' => 'Kerlitao da Sonn',
            'sexo' => 2,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);
    
        DB::table('clientes')->insert([
            'name' => 'Jessey Plas Tidu',
            'name_mother' => 'Kerteed Abzudiu',
            'name_father' => 'Hernan Canoas',
            'sexo' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Query Poort Fertee',
            'name_mother' => 'Obasias Ob Sant',
            'name_father' => 'Lerren Juik Orre',
            'sexo' => 2,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Fakiysis Easly Jurtee',
            'name_mother' => 'Franquesstein Kerly Basis',
            'name_father' => 'Lerren Juik Orre II',
            'sexo' => 2,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Quenn Balil',
            'name_mother' => 'Obas Oba Ob a',
            'name_father' => 'Lauroan Kare',
            'sexo' => 2,
            'est_civil' => 1,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Verteng Nurlet',
            'name_mother' => 'Hioran Blass',
            'name_father' => 'Lokamian Kerlitazzo',
            'sexo' => 2,
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '968.521.980-06',
            'rg' => '47.690.105-4',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'fukiss@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Tery Akinn',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'rosdasl@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Primmert Jurll',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Flixerr Ryuss',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Antonioz Kert',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'rob32423val@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Pratiquiss Poulus',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'roasfdfval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Nexxti Flerps',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'r324l@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Kross Miller Silva',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Tudises Abdaires',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Novelos Jertes Tunes',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'Novelos@hotmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Noterlus Amirianos Eesy',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'notes_body@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Blinks Securitts Santos',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Nonos Nanos K',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers I',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers II',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers III',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers IV',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers V',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers VI',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers VII',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers VIII',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers IX',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Marshall Mathers X',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Supos Sales Said',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'John Lok',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'James Nunes',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Neverlino Nver I',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Neverlino Nver II',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Neverlino Nver III',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Neverlino Nver IV',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Neverlino Nver V',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Neverlino Nver I',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Neverlino Nver II',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Neverlino Nver III',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'Teresopolos',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);

        DB::table('clientes')->insert([
            'name' => 'N Nver V',
            'name_mother' => 'Sunizall Ango',
            'name_father' => 'Chaleb2es Karll',
            'sexo' => 1, 
            'dt_born'=>date('Y-m-d',strtotime('1980-03-14')),
            'est_civil' => 1,
            'cpf' => '349.000.000-51',
            'rg' => '34.165.232-5',
            'rne' => '',
            'phone' => '(11)912341234',
            'email' => 'robherval@gmail.com',
            'cep' => '18078-792',
            'address' => 'Rua Myrna Barbosa Raszl',
            'number' => '123',
            'comple' => 'Logo ali',
            'neigh' => 'Jardim Sorocaba Park',
            'country' => 'Brazil',
            'uf' => 'SP',
            'city' => 'Sorocaba',
            'created_at'=>date('Y-m-d'),
        ]);
    }
}
